config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tours, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :guides, only: [:index, :show] do
    member do
      get :detail
    end
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]

    resources :tours, only: [:new, :create, :edit, :update, :index, :destroy]

    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  namespace :visitor do
    resources :bookings, only: [:index] do
      member do
        patch :cancel
      end
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessor :day

  belongs_to :guide, class_name: "User"
  belongs_to :visitor, class_name: "User"
  belongs_to :tour

  has_many :reviews, dependent: :destroy

  def hours
    ((check_out - check_in) / 60) / 60
  end

  # validates :check_in, :check_out, :date, presence: true
  # status
end

app/controllers/account/bookings_controller.rb
class Account::BookingsController < ApplicationController
before_action :find_booking, only: [:accept, :decline]

  def index #view
    if user_signed_in?
      @bookings = current_user.requests
      @guide = current_user
    else
      redirect_to root_path
    end
  end

  def accept
   @booking.update(status: "accepted" )
   redirect_to account_bookings_path
  end

  def decline
    @booking.update(status: "declined" )
    redirect_to account_bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :find_tour, only: [:new, :create]

  def new # view
    @booking = Booking.new
    session[:user_return_to] = request.original_url
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.day == "today"
      @booking.date = Date.today
    else
      @booking.date = Date.tomorrow
    end

    @booking.guide = @tour.user
    @booking.tour = @tour
    @booking.visitor = current_user
    @booking.hour_rate = @tour.user.hour_rate
    @booking.total_price = @booking.hours * @booking.hour_rate
    @booking.status = :pending

    if @booking.save!
      redirect_to visitor_bookings_path
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:day, :check_in, :check_out)
  end

  def find_tour
    @tour = Tour.find(params[:tour_id])
  end
end

app/controllers/visitor/bookings_controller.rb
class Visitor::BookingsController < ApplicationController
  before_action :find_booking, except: [:index]

  def index #view
    if user_signed_in?
      @bookings = current_user.trips.sort {|trip1, trip2| trip2[:date] <=> trip1[:date]}
      @visitor = current_user



      # @bookings = current_user.trips.reject do |booking|
      #   booking.status == 'cancel'
      # end
    else
      redirect_to root_path
    end
  end

  # def show
  # end

  def cancel
    @booking.update(status: 'cancel')
    redirect_to visitor_bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/views/visitor/bookings/index.html.erb
<div class="body-bookings-visitor">

  <%= render "shared/navbarback"%>

  <div class="banner-bookings-visitor">
    <% if @bookings.size == 1 %>
      <h1>
      <b>Congratulations</b>
      <%= @visitor.first_name %>, <br>
      with your first adventure!
      </h1>
    <% elsif @bookings.size > 1 %>
      <h1><b>Congratulations</b>
      <%= @visitor.first_name %>, <br>
      with a new booking!
      </h1>
    <% else %>
      <h1>You have no bookings</h1>
    <% end %>
  </div>
  <div class="header-line"></div>

      <div class="content-booking-visitor">
        <div class="container" id="map">
          <div class="basic-bookings-card">
            <div class="row">
            <% @bookings.each do |booking| %>
              <div class="col-xs-12 col-sm-6">
                <div class="bookings-card">

                  <div class="guide-name">
                  <%= booking.guide.first_name %>
                  <%= booking.guide.last_name %>
                  </div>
                  <%= link_to detail_guide_path(booking.guide), remote: true do %>

                  <%= image_tag booking.guide.photo, \
                  class: "bookings-photo" %>

                  <% end %>

                  <div class="bookings-text">
                    <div>
                      <i class="fa fa-calendar"></i>
                      <%= l(booking.date, format: "%A %d %B") %>
                    </div>
                    <div>
                      <i class="fa fa-clock-o"></i>
                      <%= l(booking.check_in, format: :hours) %> - <%= l(booking.check_out, format: :hours)%>
                    </div>
                    <div>
                    <i class="<%= category_icon_css_class(booking.tour.category) %>"></i>
                    <%= booking.tour.category.name %>
                    </div>
                  </div>

                  <div class="status-booking text-center">
                    <% if booking.status == "pending" %>
                      <%= link_to cancel_visitor_booking_path(booking), \
                        method: :patch, data: {confirm: 'Are you sure to cancel this booking?'}, \
                        class: "cancel-button" do %>
                          <i class="fa fa-times-circle-o icon-cancel-button"></i>
                          <i class="fa fa-circle icon-cancel-button-back" style="color: #EEEEEE"></i>
                        <% end %>
                    <% end %>
                    <div class="price-info">
                      <p>
                      <i class="fa fa-euro"></i>
                      <%= booking.total_price %>
                      </p>
                    </div>

                    <div>
                      <% if booking.status == "pending" %>
                        <div style="color:#F7DB61;">
                          <%= booking.status %>
                        </div>
                      <% elsif booking.status == "confirm" %>
                        <div style="color: #5cb85c;;">
                          <%= booking.status %>
                        </div>

                      <% else %>
                        <div style="color: #d9534f;">
                          <%= booking.status %>
                        </div>
                      <% end %>
                    </div>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/visitor/bookings/show.html.erb
<div class="text-center">
  <h1>Visitor Bookings Show</h1>

  <p><strong><%= @booking.guide.first_name %> <%= @booking.guide.last_name %></strong></p>


</div>
<%#= link_to "Cancel booking", cancel_visitor_booking(@booking), method: :patch, class: "btn btn-primary"%>