config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tours, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :guides, only: [:index, :show] do
    member do
      get :detail
    end
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]

    resources :tours, only: [:new, :create, :edit, :update, :index, :destroy]

    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  namespace :visitor do
    resources :bookings, only: [:index] do
      member do
        patch :cancel
      end
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessor :day

  belongs_to :guide, class_name: "User"
  belongs_to :visitor, class_name: "User"
  belongs_to :tour

  has_many :reviews, dependent: :destroy

  def hours
    ((check_out - check_in) / 60) / 60
  end

  # validates :check_in, :check_out, :date, presence: true
  # status
end

app/controllers/account/bookings_controller.rb
class Account::BookingsController < ApplicationController
before_action :find_booking, only: [:accept, :decline]

  def index #view
    if user_signed_in?
      @bookings = current_user.requests
      @guide = current_user
    else
      redirect_to root_path
    end
  end

  def accept
   @booking.update(status: "accepted" )
   redirect_to account_bookings_path
  end

  def decline
    @booking.update(status: "declined" )
    redirect_to account_bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :find_tour, only: [:new, :create]

  def new # view
    @booking = Booking.new
    session[:user_return_to] = request.original_url
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.day == "today"
      @booking.date = Date.today
    else
      @booking.date = Date.tomorrow
    end

    @booking.guide = @tour.user
    @booking.tour = @tour
    @booking.visitor = current_user
    @booking.hour_rate = @tour.user.hour_rate
    @booking.total_price = @booking.hours * @booking.hour_rate
    @booking.status = :pending

    if @booking.save!
      redirect_to visitor_bookings_path
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:day, :check_in, :check_out)
  end

  def find_tour
    @tour = Tour.find(params[:tour_id])
  end
end

app/controllers/visitor/bookings_controller.rb
class Visitor::BookingsController < ApplicationController
  before_action :find_booking, except: [:index]

  def index #view
    if user_signed_in?
      @bookings = current_user.trips.sort {|trip1, trip2| trip2[:date] <=> trip1[:date]}
      @visitor = current_user



      # @bookings = current_user.trips.reject do |booking|
      #   booking.status == 'cancel'
      # end
    else
      redirect_to root_path
    end
  end

  # def show
  # end

  def cancel
    @booking.update(status: 'cancel')
    redirect_to visitor_bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/views/bookings/_newlayout.html.erb
  <div class="container">
    <div class="row">
      <div class="header-form">
        <h1>Book your guide <b><%= @tour.user.first_name  %> !</b></h1>
        <p>In the category <%= @tour.category.name  %></p>
        <br>
        <div class="header-line-white"></div>
      </div>
      <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4 padded">
        <div class="container-boeking">
          <div class="guide text-center">
            <h2>- <%= @tour.user.first_name %> <%= @tour.user.last_name %> -</h2>
            <div class="price">€<%= @tour.user.hour_rate  %></div>
            <%= link_to guide_path(@tour.user) do %>
              <% if @tour.user.provider %>
                <%= image_tag @tour.user.picture, class: "guide-photo"  %>
              <% elsif @tour.user.photo.present? %>
                <%= image_tag @tour.user.photo, class: "guide-photo"  %>
              <% else %>
                <%= image_tag "default-user-photo.png", class: "guide-photo"  %>
              <% end %>
            <% end %>
            <div class="stars">
              <% if @tour.user.rating %>
              <% @tour.user.rating.times do %>
              <i class="fa fa-star"></i>
              <% end %>
              <% (5 - @tour.user.rating).times do %>
              <i class="fa fa-star-o"></i>
              <% end %>
              <% end %>
            </div>
            <hr>
          </div>
          <div class="form">
            <%= simple_form_for(@booking, url: tour_bookings_path(@tour)) do |f| %>
            <%= f.error_notification %>
            <%#= f.input :day, as: :radio_buttons, collection: \
          [['Today', 'today'], ['Tomorrow', 'tomorrow']], selected: 'today' %>

            <div class='new-booking-radios'>
              <%= f.radio_button :day, 'today', id: 'today', :checked => true %>
              <%= label :day, 'Today', class: "selected-day", for: 'today'  %>
            </div>
            <div class='new-booking-radios'>
              <%= f.radio_button :day, 'tommorrow', id: 'tommorrow' %>
              <%= label :day, 'Tommorrow', for: 'tommorrow', class: "selected-day" %>
            </div>
            <div class="dates">
              <div>
                <%= f.input :check_in, minute_step: 15, input_html: { class: 'book-date' } %>
              </div>
              <div>
                <div class="input-time">
                  <%= f.input :check_out, minute_step: 15, input_html: { class: 'book-date' } %>
                </div>
              </div>
            </div>
            <%= f.submit id: "button-new-booking" %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-4 text-center">
        <div class="buttons">
          <%= link_to "Homepage", root_path, :class => "button-photo" %>
          <%= link_to "Tours", tours_path, :class => "button-photo" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/bookings/new.html.erb
<div class="body-form-new">
  <div class="<%= tour_banner_css_class(@tour) %>">
    <%= render "shared/navbarspace" %>
    <%= render "bookings/newlayout" %>
    <%= render "shared/footerspace" %>
  </div>
</div>