config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tours, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :guides, only: [:index, :show] do
    member do
      get :detail
    end
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]

    resources :tours, only: [:new, :create, :edit, :update, :index, :destroy]

    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  namespace :visitor do
    resources :bookings, only: [:index] do
      member do
        patch :cancel
      end
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
<%#= render "shared/flashspace"  %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
<%#= render "shared/flashspace"  %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flashspace.html.erb
<div class="flash-space"></div>

app/views/shared/_footerspace.html.erb
<div class="space-footer"></div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-black.png", class: "logo-my48" %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%#= link_to t(".sign_in", default: "HOW IT WORKS"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%#= link_to t(".sign_in", default: "EPIC STORIES"), root_path , class: "navbar-wagon-item navbar-wagon-link" %>
    <%#= link_to t(".sign_in", default: "ABOUT"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <%= render "shared/navbarmenu"  %>

    <% else %>
    <!-- Login text link -->
    <%= link_to t(".top_call_to_action", default: "BECOME A GUIDE"), new_user_registration_path(guide: true), class: "navbar-wagon-item navbar-wagon-button btn" %>

    <%= link_to t(".top_call_to_action", default: "SIGN IN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" style="color:white;" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <!-- <li> -->
         <%#= link_to t(".sign_in", default: "How it works"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <!-- </li> -->
       <!-- <li> -->
         <%#= link_to t(".sign_in", default: "Epic stories"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <!-- </li> -->
       <!-- <li> -->
         <%#= link_to t(".sign_in", default: "About"), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <!-- </li> -->
       <% if user_signed_in? %>
        <% if current_user.guide == true %>
          <li>
            <%= link_to account_profile_path do %>
              <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
        </li>
        <% else %>
          <li>
           <%= link_to visitor_bookings_path do %>
             <i class="fa fa-book"></i>  <%= t ".profile", default: "Bookings" %>
           <% end %>
         </li>
       <% end %>
      <% if current_user.guide == true %>
        <li>
          <%= link_to account_bookings_path do %>
            <i class="fa fa-book"></i>  <%= t ".profile", default: "Bookings" %>
          <% end %>
        </li>
      <% end %>
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
          <% end %>
        </li>
       <li>
         <%= link_to destroy_user_session_path, method: :delete do %>
         <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
         <% end %>
       </li>
       <% else %>
       <li>
         <%= link_to new_user_registration_path(guide: true), class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-sign-out"></i> <%= t(".top_call_to_action", default: "Become a guide") %>
         <% end %>
       </li>
       <li>
           <%= link_to t(".top_call_to_action", default: "Sign-in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
       </li>
       <% end %>
     </ul>
   </div>
 </div>
</div>

app/views/shared/_navbarback.html.erb
<div class="navbar-background">
  <div class="cube"></div>
</div>

app/views/shared/_navbarmenu.html.erb
<div class="navbar-wagon-item">
  <div class="dropdown">
    <% if current_user.provider %>
    <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
    <% elsif current_user.photo.present? %>
    <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
    <% else %>
    <%= image_tag "default-user-photo.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
    <% end %>
    <div class="note-bullit">
      <% if current_user.guide == true %>
      <%= current_user.requests.select{|trip| trip.status == 'pending'}.length %>
      <% else %>
      <%= current_user.trips.select{|trip| trip.status == 'pending'}.length %>
      <% end %>
    </div>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <% if current_user.guide == true %>
        <li>
          <%= link_to account_profile_path do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
          <% end %>
        </li>
        <% else %>
          <li>
           <%= link_to visitor_bookings_path do %>
             <i class="fa fa-book"></i>  <%= t ".profile", default: "Bookings" %>
           <% end %>
         </li>
       <% end %>
      <% if current_user.guide == true %>
        <li>
          <%= link_to account_bookings_path do %>
            <i class="fa fa-book"></i>  <%= t ".profile", default: "Bookings" %>
          <% end %>
        </li>
          <li>
           <%= link_to account_tours_path do %>
             <i class="fa fa-file-text"></i>  <%= t ".profile", default: "Tours" %>
           <% end %>
         </li>
      <% end %>
      <li>
        <%= link_to root_path do %>
          <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbarspace.html.erb
<div class="space-navbar"></div>