config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tours, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :guides, only: [:index, :show] do
    member do
      get :detail
    end
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]

    resources :tours, only: [:new, :create, :edit, :update, :index, :destroy]

    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  namespace :visitor do
    resources :bookings, only: [:index] do
      member do
        patch :cancel
      end
    end
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :find_guide, only: [:detail, :show]

  respond_to :js, only: [:detail]

  def index #view
    @guides = User.where(guide: true)
    @booking = Booking.find(params[:id])
    @tours = Tour.all
  end

  def show #view
    @tour = @guide.tours.first
  end

  def detail
    if params[:category_id]
      @main_tour = @guide.tours.where(category_id: params[:category_id]).first
    else
      @main_tour = @guide.tours.first
    end

    @extra_tours = @guide.tours
    @extra_tours = @extra_tours.where.not(id: @main_tour.id) if @main_tour
    @reviews = Review.select { |review| review.booking.tour.user.first_name == "Emma" }
  end

  private
  def find_guide
    @guide = User.where(guide: true).find(params[:id])
  end

end

app/views/guides/_guide_card.html.erb
<div class='guide-card-container'>
  <div class="guide-card">
    <div class="guide-card-avatar" style="background-image: url(<%= guide.photo %>)">

    </div>
    <div class="guide-card-bio">
      <div class="guide-card-row">
        <h3><%= guide.first_name %> <%= guide.last_name %> </h3>
        <div class="card-action-icons">
        <!--   <div class="card-booking">
            <a href=""><i class="fa fa-phone"></i></a>
            <a href=""><i class="fa fa-envelope"></i></a>
          </div> -->
          <div class="card-rating">
            <% guide.rating.times do %>
            <i class="fa fa-star"></i>
            <% end %>
            <% (5 - guide.rating).times do %>
            <i class="fa fa-star-o"></i>
            <% end %>
          </div>
        </div>
        <p class="guide-card-bio-description"><%= guide.bio %></p>
        <p class="guide-card-bio-hour-rate"> $ <%= guide.hour_rate %> /h</p>
      </div>
    </div>
  </div>

  <div class="guide-card-information">
    <div class="guide-card-about">
      <div class="flex-card-current-category">
        <h3><i class="<%= category_icon_css_class(main_tour.category) %>"></i>
          <%= main_tour.category.name %> <span class="hrs-left"><%= guide.available_hours %> hrs remaining </span></h3>

          <div class="flex-card-booking-about">
            <p><%= main_tour.description %></p>
            <%= link_to new_tour_booking_path(main_tour), class: "button-booking" do %>

            <p>Booking</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="guide-card-information">
      <div class="guide-card-tours">
       <h4>More tours</h4>

       <% extra_tours.each do |tour| %>
       <div class="guide-card-tour">
         <i class="<%= category_icon_css_class(tour.category) %>"></i>
         <p class="booking-description"><%= tour.description %></p>
         <span class"hrs-left"><i class="time-icon mdi mdi-timelapse
"></i><%= guide.available_hours %> hrs </span>
         <%= link_to detail_guide_path(guide, category_id: tour.category_id), remote: true, class: "button-checking" do %>
         <p>Check</p>
         <% end %>
       </div>
       <% end %>
     </div>
   </div>


   <div class="guide-card-rating text-center">
     <hr>
     <div class="guide-card-avarage-rating">
      <p class="avarage-number"> <%= guide.rating %>.0</p>
      <h4>Average Rating</h4>
    </div>
  </div>

  <div class="user-card-review">
    <div class="arrow-left"></div>
    <div class="user-card-review-profile">
      <div class="user-avatar-review-letter"><span>S</span></div>
    </div>
    <div class="user-card-comment-row">
     <div class="user-card-review-comment">
      <p>Was a very helpfull session, straight to the point of what I need! Thanks!</p>
    </div>
    <div class="user-card-review-comment-footer">
      <p>Susan</p>
      <p class="date">Mar 24, 2016</p>
    </div>
  </div>
</div>


<div class="user-card-review">
  <div class="arrow-left"></div>
  <div class="user-card-review-profile">
    <div class="user-avatar-review-letter"><span>H</span></div>
  </div>
  <div class="user-card-comment-row">
   <div class="user-card-review-comment">
    <p>Lovely lady,fantastic tour great knowledge of Amsterdam. Will definately use local guides </p>
  </div>
  <div class="user-card-review-comment-footer">
    <p>Hendrik</p>
    <p class="date">Mar 25, 2016</p>
  </div>
</div>
</div>

<div class="user-card-review">
  <div class="arrow-left"></div>
  <div class="user-card-review-profile">
    <div class="user-avatar-review-letter"><span>J</span></div>
  </div>
  <div class="user-card-comment-row">
   <div class="user-card-review-comment">
    <p>Awesome tour....would do again. We took a tour from Emma in 2011 and liked it so much, we used him again when we were in Amsterdam again.</p>
  </div>
  <div class="user-card-review-comment-footer">
    <p>Jacky</p>
    <p class="date">Mar 28, 2016</p>
  </div>
</div>
</div>
</div>

app/views/guides/detail.js.erb
$('.modal-profile').addClass('is-active')
$('.modal-profile').html("<%= j render 'guides/guide_card', guide: @guide, main_tour: @main_tour, extra_tours: @extra_tours%>")

app/views/guides/index.html.erb
<h1>Guides Index</h1>

<ul>
  <% @guides.each do |guide|  %>
  <li>
  <b>id: </b>
    <%= guide.id  %> |
  <b>Guide: </b>
    <%= guide.first_name %>
    <%= guide.last_name %> |
    <i class="fa fa-map-marker"></i>
    <%= guide.street %>
    <%= guide.zipcode %>
    <%= guide.city %> |
    <i class="fa fa-phone"></i>
    <%= guide.phone %> |
    <i class="fa fa-info-circle"></i>
    <%= guide.bio %> |
    <i class="fa fa-eur"></i>
    <%= guide.hour_rate %>

    <%= link_to "See Profile", guide_path(guide), :class => "btn btn-primary btn-sm" %>
    <hr>
  </li>
<% end %>
</ul>

<%= link_to "homepage", root_path, :class => "btn btn-default btn-sm" %>

app/views/guides/show.html.erb
<%= render "shared/navbarspace" %>
<%= render 'guide_card', guide: @guide %>

<% content_for :meta_title, "#{@guide.first_name} suggest a tour at #{@guide.hour_rate} €" %>
<% content_for :meta_description, @tour.description %>
<% content_for :meta_image, @guide.photo %>